/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.c_KLOC;
import Controlador.c_archivo;
import Modelo.m_KLOC;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Clase con la vista principal de todo el programa, compuesta por dos paneles:
 * lectura de archivos y resultados.
 *
 * @author Cecivel Solano
 * @author Raúl Romero
 * @version 1.0.0
 * @since COCOMO1 1.0.0
 */
public class v_principal extends javax.swing.JFrame {

    File archivo;
    v_portada objPortada;
    int contFila = 0;
    DefaultTableModel tablaModelo;
    int numCodigo = 0;
    public static m_KLOC objM_KLOC = new m_KLOC();

    /**
     * Constructor donde se inicializan todos los componentes gráficos.
     *
     * @since COCOMO1 1.0.0
     */
    public v_principal() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.panelInicio.setVisible(true);
        this.panelResultado.setVisible(false);

        //se crea un evento que escuche los cambios del combobox para limpiar los resultados entre cada tipo de proyecto
        cmbTipos.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    Calcular();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicio = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSeleccionar = new javax.swing.JButton();
        txtMostrarRuta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnObtenerLDC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResumen = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        lblLDC = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelResultado = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        bntAtras = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblResultProductividad = new javax.swing.JLabel();
        lblResultPersonas = new javax.swing.JLabel();
        lblResultTiempo = new javax.swing.JLabel();
        lblResultEsfuerzo = new javax.swing.JLabel();
        lblResultKLOC = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblResultLDC = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbTipos = new javax.swing.JComboBox<>();
        lblCheck = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menAyuda = new javax.swing.JMenu();
        itemInformacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelInicio.setBackground(new java.awt.Color(255, 255, 255));
        panelInicio.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COCOMO");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BÁSICO");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        btnSeleccionar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSeleccionar.setText("Cargar Nuevo");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        txtMostrarRuta.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Seleccionar archivo");

        btnObtenerLDC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnObtenerLDC.setText("Obtener LDC");
        btnObtenerLDC.setEnabled(false);
        btnObtenerLDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerLDCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMostrarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(btnObtenerLDC, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMostrarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObtenerLDC, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setEnabled(false);

        tblResumen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblResumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Archivo", "Líneas de Código", "Comentarios", "Líneas en Blanco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblResumen);
        if (tblResumen.getColumnModel().getColumnCount() > 0) {
            tblResumen.getColumnModel().getColumn(0).setResizable(false);
            tblResumen.getColumnModel().getColumn(1).setResizable(false);
            tblResumen.getColumnModel().getColumn(2).setResizable(false);
            tblResumen.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Archivos cargados");

        btnContinuar.setBackground(new java.awt.Color(255, 102, 51));
        btnContinuar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.setEnabled(false);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        lblLDC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Total de Líneas De Código (LDC):");

        panelInicio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInicio.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInicio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInicio.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInicio.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInicio.setLayer(btnContinuar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInicio.setLayer(lblLDC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInicio.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblLDC, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGap(0, 355, Short.MAX_VALUE)
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLDC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelResultado.setBackground(new java.awt.Color(255, 255, 255));
        panelResultado.setOpaque(true);
        panelResultado.setPreferredSize(new java.awt.Dimension(580, 515));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RESULTADOS");

        bntAtras.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bntAtras.setText("Atrás");
        bntAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAtrasActionPerformed(evt);
            }
        });

        jLayeredPane1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("KLOC:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Esfuerzo:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Tiempo requerido:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setText("Número de personas:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setText("Productividad:");

        lblResultProductividad.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        lblResultPersonas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        lblResultTiempo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        lblResultEsfuerzo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        lblResultKLOC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setText("LDC:");

        lblResultLDC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblResultProductividad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblResultPersonas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblResultTiempo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblResultEsfuerzo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblResultKLOC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblResultLDC, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblResultProductividad, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(lblResultPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblResultTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblResultEsfuerzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblResultKLOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblResultLDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblResultLDC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResultKLOC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblResultEsfuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResultTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResultPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lblResultProductividad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        cmbTipos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Orgánico", "Semi-separado", "Incrustado" }));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modelo Básico" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTipos, 0, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbTipos, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(lblCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("COCOMO");

        panelResultado.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelResultado.setLayer(bntAtras, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelResultado.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelResultado.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelResultado.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultadoLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bntAtras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1)
                .addGap(18, 18, 18)
                .addComponent(bntAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menAyuda.setText("Ayuda");

        itemInformacion.setText("Fórmulas utilizadas");
        itemInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInformacionActionPerformed(evt);
            }
        });
        menAyuda.add(itemInformacion);

        menu.add(menAyuda);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
        );

        panelInicio.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Abre diálogo para seleccionar un archivo y habilita los botones "Obtener
     * LDC" y "Continuar".
     *
     * @param evt
     * @since COCOMO1 1.0.0
     */
    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        JFileChooser seleccionar = new JFileChooser();
        seleccionar.showOpenDialog(this);       //abre ventana para seleccionar archivo

        archivo = seleccionar.getSelectedFile();       //archivo seleccionado se almacena en una variable

        if (archivo != null) {                    //validar que se haya seleccionado y cargado un archivo
            txtMostrarRuta.setText(archivo.getAbsolutePath());      //mostrar en la caja de texto la ruta del archivo seleccionado
            habilitarBotonObtenerLDC();
            deshabilitarBotonContinuar();
        } else {
            txtMostrarRuta.setText("");             //limpiar caja de texto en caso de no seleccionar ningún archivo
        }

    }//GEN-LAST:event_btnSeleccionarActionPerformed
    /**
     * Controla qué fórmulas aplicar de acuerdo al Tipo de Proyecto
     * seleccionado.
     *
     * @param evt
     * @since COCOMO1 1.0.0
     */
    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        if (validarTotalLDC(objM_KLOC.getLDC())) {  //comprueba si el total de LDC es mayor a 1000

            if (objM_KLOC.getLDC() <= 50000) {         //si las lineas de codigo son menores a 50000 se trata de un proyecto orgánico
                cmbTipos.setSelectedItem("Orgánico");
            } else if (objM_KLOC.getLDC() <= 300000) { //si las lineas de codigo son menores a 300000 se trata de un proyecto semi-separado
                cmbTipos.setSelectedItem("Semi-separado");
            } else {                //si las lineas de codigo son mayores a 300000 se trata de un proyecto incrustado
                cmbTipos.setSelectedItem("Incrustado");
            }
            this.panelInicio.setVisible(false);
            this.panelResultado.setVisible(true);
            lblResultLDC.setText(String.valueOf(objM_KLOC.getLDC()));     //mostrar LDC final en panel resultados
            Calcular();
            lblResultKLOC.setText(String.valueOf(String.format("%.2f", objM_KLOC.getKLOC())));   //mostrar KLOC final en panel resultados

        } else {
            JOptionPane.showMessageDialog(null, "El número de LDC es menor a 1000, pruebe agregando más archivos.", "No fue posible aplicar COCOMO", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnContinuarActionPerformed
    /**
     * Comprueba si el total de Líneas de Código (LDC) es mayor a 1000.
     *
     * @param LDC
     * @return Valor booleano
     * @since COCOMO1 1.0.0
     */
    public static boolean validarTotalLDC(int LDC) {  //comprueba si el total de LDC es mayor a 1000
        boolean bool = false;
        if (LDC >= 1000) {
            bool = true;
        } else {
            bool = false;
        }
        return bool;
    }

    /**
     * Controla que el archivo seleccionado sea válido, solicita llenar la
     * tabla, habilita el botón "Continuar" y deshabilita el botón "Obtenet
     * LDC".
     *
     * @param evt
     * @since COCOMO1 1.0.0
     */
    private void btnObtenerLDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerLDCActionPerformed

        c_archivo objC_Archivo = new c_archivo();

        try {
            if (archivo.canRead()) {            //comprobar si se seleccionó un archivo

                if (objC_Archivo.formato(archivo)) {    //comprobar si es un formato de archivo soportado

                    objC_Archivo.leer(archivo);     //lee y cuenta las lineas de código

                    llenarTabla(objC_Archivo.getNumCodigo(), objC_Archivo.getNumComent(), objC_Archivo.getNumBlanco());

                    habilitarBotonContinuar();
                    deshabilitarBotonObtenerLDC();
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Archivo ilegible. \nError: " + e);
        }


    }//GEN-LAST:event_btnObtenerLDCActionPerformed
    /**
     * Oculta el panel de Resultados y muestra el panel de Inicio
     *
     * @param evt
     * @since COCOMO1 1.0.0
     */
    private void bntAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAtrasActionPerformed

        panelResultado.setVisible(false);
        panelInicio.setVisible(true);
    }//GEN-LAST:event_bntAtrasActionPerformed
    /**
     * Presentar las fórmulas utilizadas en el software definidas por el COCOMO
     * Básico
     *
     * @param evt
     * @since COCOMO1 1.0.0
     */
    private void itemInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInformacionActionPerformed
        // TODO add your handling code here:
        v_formulas objFormulas = new v_formulas();
        objFormulas.setVisible(true);
    }//GEN-LAST:event_itemInformacionActionPerformed
    /**
     * Método encargado de hacer los cálculos para determinar COCOMO Básico de
     * acuerdo a las fórmulas del mismo
     *
     * @since COCOMO1 1.0.0
     */
    public void Calcular() {
        /*
            E = ab(KLOC)bb
            Tdev = cb(e)db
            N = E/Tdev
            Pr = LDC/E
            
         */
        double Ab, Bb, Cb, Db;
        int LDC = objM_KLOC.getLDC();
        //y lo transforma a kilo lineas de codigo, dividiendo para 1000
        //System.out.println("valor LDC: " + objM_KLOC.getLDC());
        double KLOC = (double) objM_KLOC.getLDC() / 1000;
        //  System.out.println(KLOC + "       ");
        objM_KLOC.setKLOC(KLOC);                  //asignat al objeto el valor de KLOC

        String strTipoProyecto = (String) cmbTipos.getSelectedItem();       //obtiene el valor del item seleccionando
        switch (strTipoProyecto) {
            case "Orgánico":
                //asignar valores de acuerdo al tipo de proyecto
                Ab = 2.4;
                Bb = 1.05;
                Cb = 2.5;
                Db = 0.38;

                //  calcular ESFUERZO por el proyecto, en persona-mes   Esfuerzo = Ab * (KLOC) ^ Bb
                double E = Ab * Math.pow(KLOC, Bb);
                lblResultEsfuerzo.setText(Math.round(E) + " personas-mes");           //mostrar valor del esfuerzo

                //  calcular tiempo requerido por el proyecto en meses  Tiempo Requerido = Cb * (esfuerzos) Db
                double Tdev = Cb * Math.pow(E, Db);
                lblResultTiempo.setText(Math.round(Tdev) + " meses");           //mostrar valor del tiempo requerido

                //  calcular número de personas requerido por el proyecto
                double N = E / Tdev;
                lblResultPersonas.setText(Math.round(N) + " personas");           //mostrar el número de personas requeridas

                //  calcular la productividad
                double Pr = LDC / E;
                lblResultProductividad.setText(String.format("%.2f", Pr) + "");           //mostrar productividad, redondeando a 2 decimales
                break;
            case "Semi-separado":
                //asignar valores de acuerdo al tipo de proyecto
                Ab = 3;
                Bb = 1.12;
                Cb = 2.5;
                Db = 0.35;
                //  calcular ESFUERZO por el proyecto, en persona-mes   Esfuerzo = Ab * (KLOC) ^ Bb
                //Match.pow usado para elevar a una potencia
                E = Ab * Math.pow(KLOC, Bb);
                //mostrar valor del esfuerzo
                //Match.round usado para redondear
                lblResultEsfuerzo.setText(Math.round(E) + " personas-mes");

                //  calcular tiempo requerido por el proyecto en meses  Tiempo Requerido = Cb * (esfuerzos) Db
                Tdev = Cb * Math.pow(E, Db);
                lblResultTiempo.setText(Math.round(Tdev) + " meses");           //mostrar valor del tiempo requerido

                //  calcular número de personas requerido por el proyecto
                N = E / Tdev;
                lblResultPersonas.setText(Math.round(N) + " personas");           //mostrar el número de personas requeridas

                //  calcular la productividad
                Pr = LDC / E;
                lblResultProductividad.setText(String.format("%.2f", Pr) + "");           //mostrar productividad, redondeando a 2 decimales
                break;
            case "Incrustado":
                //asignar valores de acuerdo al tipo de proyecto
                Ab = 3.6;
                Bb = 1.2;
                Cb = 2.5;
                Db = 0.32;
                //  calcular ESFUERZO por el proyecto, en persona-mes   Esfuerzo = Ab * (KLOC) ^ Bb
                //Match.pow usado para elevar a una potencia
                E = Ab * Math.pow(KLOC, Bb);
                //mostrar valor del esfuerzo
                //Match.round usado para redondear
                lblResultEsfuerzo.setText(Math.round(E) + " personas-mes");

                //  calcular tiempo requerido por el proyecto en meses  Tiempo Requerido = Cb * (esfuerzos) Db
                Tdev = Cb * Math.pow(E, Db);
                lblResultTiempo.setText(Math.round(Tdev) + " meses");           //mostrar valor del tiempo requerido

                //  calcular número de personas requerido por el proyecto
                N = E / Tdev;
                lblResultPersonas.setText(Math.round(N) + " personas");           //mostrar el número de personas requeridas

                //  calcular la productividad
                Pr = LDC / E;
                lblResultProductividad.setText(String.format("%.2f", Pr) + "");           //mostrar productividad, redondeando a 2 decimales
                break;

            default:
                break;
        }
    }

    /**
     * Inserta las filas a la tabla de acuerdo a cada archivo leído.
     *
     * @param numCodigo
     * @param numComent
     * @param numBlanco
     * @since COCOMO1 1.0.0
     */
    public void llenarTabla(int numCodigo, int numComent, int numBlanco) {

        tablaModelo = (DefaultTableModel) tblResumen.getModel();
        String fila[] = new String[4];
        contFila++;
        fila[0] = String.valueOf(contFila);
        fila[1] = String.valueOf(numCodigo);
        fila[2] = String.valueOf(numComent);
        fila[3] = String.valueOf(numBlanco);
        tablaModelo.addRow(fila);
        //System.out.println("total de lineas: \nblanco: " + numBlanco + " codigo: " + numCodigo + " coment: " + numComent);

        c_KLOC objC_KLOC = new c_KLOC();
        objC_KLOC.SumatoriaLDC(numCodigo);  //sumatoria de LDC de cada archivo

        lblLDC.setText(String.valueOf(objM_KLOC.getLDC())); //mostrar sumatoria total de LDC
    }

    /**
     * Método para deshabilitar el botón llamado "Continuar"
     *
     * @since COCOMO1 1.0.0
     */
    private void deshabilitarBotonContinuar() {
        //deshabilitar boton Continuar
        btnContinuar.setEnabled(false);
    }

    /**
     * Método para habilitar el botón llamado "Continuar"
     *
     * @since COCOMO1 1.0.0
     */
    private void habilitarBotonContinuar() {
        //habilitar boton de continuar a resultados
        if (objM_KLOC.getLDC() != 0) {
            btnContinuar.setEnabled(true);
        }
    }

    /**
     * Método para habilitar el botón llamado "Obtener LDC"
     *
     * @since COCOMO1 1.0.0
     */
    private void habilitarBotonObtenerLDC() {
        //habilitar boton de Obtener LDC
        btnObtenerLDC.setEnabled(true);
    }

    /**
     * Método para deshabilitar el botón llamado "Obtener LDC"
     *
     * @since COCOMO1 1.0.0
     */
    private void deshabilitarBotonObtenerLDC() {
        //deshabilitar boton Obtener LDC
        btnObtenerLDC.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new v_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAtras;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnObtenerLDC;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox<String> cmbTipos;
    private javax.swing.JMenuItem itemInformacion;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCheck;
    public static javax.swing.JLabel lblLDC;
    private javax.swing.JLabel lblResultEsfuerzo;
    private javax.swing.JLabel lblResultKLOC;
    private javax.swing.JLabel lblResultLDC;
    private javax.swing.JLabel lblResultPersonas;
    private javax.swing.JLabel lblResultProductividad;
    private javax.swing.JLabel lblResultTiempo;
    private javax.swing.JMenu menAyuda;
    private javax.swing.JMenuBar menu;
    private javax.swing.JLayeredPane panelInicio;
    private javax.swing.JLayeredPane panelResultado;
    public javax.swing.JTable tblResumen;
    private javax.swing.JTextField txtMostrarRuta;
    // End of variables declaration//GEN-END:variables
}
